data:
  ratio: 0.1
  n_samples: 100000
  n_features: 20
  n_informative: 7
  random_state: 7
  target_randomness: 0.5
  fix_imbalance_strategy: "nothing"

model:
  logistic: 
    C:
      - 0
      - 0.01
      - 0.05
      - 0.1
      - 0.5   
      - 1
    max_iter: 
      - 1000
    random_state: 
      - 7
  xgboost:
    n_estimators: 
      - 100
      - 200
    max_depth:
      - 4
      - 6
    eta:
      - 0.01
      - 0.05